[package]
name = "gamenet_ddnet"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
arrayvec = "0.5.2"
buffer = "0.1.9"
common = { path = "../../common/" }
gamenet_common = { path = "../common/" }
packer = { path = "../../packer/", features = ["uuid"] }
uuid = "0.8.1"
warn = ">=0.1.1,<0.3.0"
