[package]
name = "snapshot"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
buffer = "0.1.9"
common = { path = "../common/" }
gamenet_teeworlds_0_6 = { path = "../gamenet/teeworlds-0.6/" }
packer = { path = "../packer/" }
vec_map = "0.8.0"
warn = ">=0.1.1,<0.3.0"
