name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - stable
          - 1.41.1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test
      - run: cargo bench

  check-generated:
    name: Check that generated files match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./generate_all
      - run: test -z "$(git status --porcelain)"
