name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
        include:
          - os: ubuntu-latest
            rust: 1.63.0
          - os: ubuntu-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: Swatinem/rust-cache@v2
      # `demo` crate doesn't work with the MSRV.
      - name: Exclude `demo` crate from MSRV
        run: sed -i -e 's/"demo",//' -e 's/"tools",//' Cargo.toml; cargo update --workspace
        if: ${{ matrix.rust != 'stable' && matrix.rust != 'nightly' }}
      - run: cargo build --locked
      - run: cargo test --locked
      - run: cargo bench --locked
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.rust == 'stable' }}
        with:
          path: |
            target
            !target/**/*.d
            !target/**/*.rlib
            !target/**/.cargo-lock
            !target/**/.fingerprint
            !target/**/CACHEDIR.TAG
            !target/**/build
            !target/**/deps
            !target/**/incremental
          name: libtw2-${{ matrix.os }}

  build-uniffi:
    name: Build uniffi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: uniffi
      - run: cd uniffi; cargo build --locked
      - run: cd uniffi; cargo test --locked
      - run: cd uniffi; cargo bench --locked

  check-generated:
    name: Check that generated files match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./generate_all
      - run: test -z "$(git status --porcelain)"

  check-rustfmt:
    name: Check that everything is rustfmtted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --check
